### ISSUE TITLE
好无聊啊。。

### ISSUE THREAD

**Issue by TobbHuang** [StarbucksSmallTeam/TWWriteTest#1]
上班好无聊啊。。pm迟迟弄不出来需求。。

**Comment by Godning** [comment]
今天组长问我走不走逆向，我有点心动了，不过还得先搞完手头的再说。

**Comment by TobbHuang** [comment]
这年头，ML才是王道啊
快去搞ML

**Comment by Godning** [comment]
[POS机训练营](http://www.codefordream.com/courses/js-pos-boot-camp/sections)真是个神奇的练习
我们组有ML，但是不太想去

**Comment by TobbHuang** [comment]
html css js
似乎是前端的练习？

**Comment by Godning** [comment]
是的，当然还有算法的练习比如scip的练习

**Comment by TobbHuang** [comment]
开始开发啦
虽然是挺简单的功能。。
